<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Bab al Awir — Dummy data store (no database)
    |--------------------------------------------------------------------------
    | All content is hardcoded here and surfaced through the API controllers.
    | Prices are expressed in United Arab Emirates Dirhams (AED / د.إ).
    */

    'brand' => [
        'name' => 'Bab al Awir Supermarket',
        'tagline' => 'Fresh every day, for every home',
        'tagline_ar' => 'طازج كل يوم، لكل بيت',
        'currency' => 'AED',
        'currency_symbol' => 'د.إ',
        'primary_color' => '#124634',
        'support_email' => 'care@babalawir.ae',
        'support_phone' => '+971 4 000 0000',
        'founded_year' => 2018,
        'description' => 'Bab al Awir Supermarket brings together the everyday essentials of the Gulf under one calm, dependable roof. From fresh produce to household staples, we serve homes across the UAE and Saudi Arabia with friendly service and fair prices.',
        'description_ar' => 'يجمع سوبر ماركت باب العوير أساسيات الخليج اليومية تحت سقف واحد هادئ وموثوق. من المنتجات الطازجة إلى مستلزمات المنزل، نخدم المنازل في الإمارات والسعودية بخدمة ودودة وأسعار عادلة.',
        'values' => [
            ['key' => 'freshness', 'icon' => '🌿', 'label_en' => 'Uncompromising Freshness', 'label_ar' => 'نضارة لا مثيل لها', 'desc_en' => 'We source our produce daily to ensure every bite is as fresh as it gets.', 'desc_ar' => 'نحصل على منتجاتنا يومياً لضمان أقصى درجات النضارة.'],
            ['key' => 'community', 'icon' => '🤝', 'label_en' => 'Rooted in Community', 'label_ar' => 'متجذرون في المجتمع', 'desc_en' => 'Every store is a neighbourhood hub where familiar faces and friendly service matter.', 'desc_ar' => 'كل فرع هو مركز حي حيث الوجوه المألوفة والخدمة الودودة.'],
            ['key' => 'fairness', 'icon' => '⚖️', 'label_en' => 'Fair & Transparent', 'label_ar' => 'منصف وشفاف', 'desc_en' => 'Honest pricing with no hidden fees. What you see is what you pay.', 'desc_ar' => 'أسعار صادقة بدون رسوم خفية. ما تراه هو ما تدفعه.'],
            ['key' => 'sustainability', 'icon' => '♻️', 'label_en' => 'Sustainable Choices', 'label_ar' => 'خيارات مستدامة', 'desc_en' => 'We champion local farmers and reduce plastic waste across our supply chain.', 'desc_ar' => 'ندعم المزارعين المحليين ونقلل النفايات البلاستيكية في سلسلة التوريد.'],
        ],
    ],

    'regions' => [
        [
            'code' => 'ae',
            'name' => 'United Arab Emirates',
            'name_ar' => 'الإمارات العربية المتحدة',
            'flag' => 'ae',
            'currency' => 'AED',
            'currency_symbol' => 'د.إ',
            'delivery_fee' => 15.00,
            'free_delivery_min' => 100.00,
            'timezone' => 'Asia/Dubai',
        ],
        [
            'code' => 'sa',
            'name' => 'Saudi Arabia',
            'name_ar' => 'المملكة العربية السعودية',
            'flag' => 'sa',
            'currency' => 'SAR',
            'currency_symbol' => '﷼',
            'delivery_fee' => 20.00,
            'free_delivery_min' => 150.00,
            'timezone' => 'Asia/Riyadh',
        ],
    ],

    'languages' => [
        ['code' => 'en', 'name' => 'English',   'native' => 'English',          'dir' => 'ltr', 'font' => 'Inter'],
        ['code' => 'ar', 'name' => 'Arabic',    'native' => 'العربية',          'dir' => 'rtl', 'font' => 'Tajawal'],
        ['code' => 'ml', 'name' => 'Malayalam', 'native' => 'മലയാളം',          'dir' => 'ltr', 'font' => 'Noto Sans Malayalam'],
        ['code' => 'ta', 'name' => 'Tamil',     'native' => 'தமிழ்',            'dir' => 'ltr', 'font' => 'Noto Sans Tamil'],
    ],

    'sections' => [
        ['key' => 'home',      'label_en' => 'Home',      'label_ar' => 'الرئيسية', 'label_ml' => 'ഹോം',       'label_ta' => 'முகப்பு'],
        ['key' => 'categories','label_en' => 'Categories','label_ar' => 'الفئات',   'label_ml' => 'വിഭാഗങ്ങൾ', 'label_ta' => 'வகைகள்'],
        ['key' => 'products',  'label_en' => 'Products',  'label_ar' => 'المنتجات', 'label_ml' => 'ഉൽപ്പന്നങ്ങൾ','label_ta' => 'தயாரிப்புகள்'],
        ['key' => 'offers',    'label_en' => 'Offers',    'label_ar' => 'العروض',   'label_ml' => 'ഓഫറുകൾ',    'label_ta' => 'சலுகைகள்'],
        ['key' => 'about',     'label_en' => 'About',     'label_ar' => 'من نحن',   'label_ml' => 'ഞങ്ങളെക്കുറിച്ച്','label_ta' => 'எங்களைப் பற்றி'],
        ['key' => 'contact',   'label_en' => 'Contact',   'label_ar' => 'اتصل بنا', 'label_ml' => 'ബന്ധപ്പെടുക', 'label_ta' => 'தொடர்பு'],
        ['key' => 'profile',   'label_en' => 'Profile',   'label_ar' => 'الملف الشخصي','label_ml' => 'പ്രൊഫൈൽ', 'label_ta' => 'சுயவிவரம்'],
    ],

    'categories' => [
        ['id' => 1,  'slug' => 'fruits',          'icon' => '🍎', 'name_en' => 'Fruits',                  'name_ar' => 'فواكه',                'name_ml' => 'പഴങ്ങൾ',                  'name_ta' => 'பழங்கள்',                 'desc_en' => 'Fresh hand-picked fruits from around the world',                'desc_ar' => 'فواكه طازجة منتقاة من جميع أنحاء العالم', 'image' => 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 2,  'slug' => 'vegetables',      'icon' => '🥦', 'name_en' => 'Vegetables',              'name_ar' => 'خضروات',               'name_ml' => 'പച്ചക്കറികൾ',             'name_ta' => 'காய்கறிகள்',              'desc_en' => 'Farm-fresh seasonal vegetables',                                'desc_ar' => 'خضروات موسمية طازجة من المزرعة', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 3,  'slug' => 'juices',          'icon' => '🧃', 'name_en' => 'Juices',                  'name_ar' => 'عصائر',                'name_ml' => 'ജ്യൂസുകൾ',               'name_ta' => 'சாறுகள்',                  'desc_en' => 'Fresh and packaged fruit juices',                               'desc_ar' => 'عصائر فواكه طازجة ومعلبة', 'image' => 'https://images.unsplash.com/photo-1598871265419-c471c1b43a6c?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 4,  'slug' => 'dairy-eggs',     'icon' => '🥛', 'name_en' => 'Dairy & Eggs',            'name_ar' => 'منتجات الألبان والبيض','name_ml' => 'പാലും മുട്ടയും',         'name_ta' => 'பால் மற்றும் முட்டை',     'desc_en' => 'Fresh milk, cheese, butter and farm eggs',                      'desc_ar' => 'حليب وجبن وزبدة وبيض مزرعة طازج', 'image' => 'https://images.unsplash.com/photo-1628088062854-b1870b1e2079?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 5,  'slug' => 'bakery-bread',    'icon' => '🍞', 'name_en' => 'Bakery & Bread',          'name_ar' => 'مخبوزات وخبز',         'name_ml' => 'ബേക്കറിയും റൊട്ടിയും',  'name_ta' => 'பேக்கரி மற்றும் ரொட்டி',  'desc_en' => 'Daily breads, biscuits and baked goods',                        'desc_ar' => 'خبز يومي وبسكويت ومنتجات مخبوزة', 'image' => 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 6,  'slug' => 'snacks-biscuits', 'icon' => '🍪', 'name_en' => 'Snacks & Biscuits',      'name_ar' => 'وجبات خفيفة وبسكويت',  'name_ml' => 'ലഘുഭക്ഷണവും ബിസ്കറ്റും','name_ta' => 'தின்பண்டங்கள் மற்றும் பிஸ்கட்','desc_en' => 'Chips, chocolates, biscuits and candies',                        'desc_ar' => 'رقائق وشوكولاتة وبسكويت وحلوى', 'image' => 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 7,  'slug' => 'rice',            'icon' => '🍚', 'name_en' => 'Rice',                    'name_ar' => 'أرز',                  'name_ml' => 'അരി',                    'name_ta' => 'அரிசி',                    'desc_en' => 'Basmati, Sona Masoori, Jeerakasala and more',                  'desc_ar' => 'بسمتي، سونا ماسوري، جيراكاسالا والمزيد', 'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 8,  'slug' => 'pulses-grams',    'icon' => '🌱', 'name_en' => 'Pulses & Grams',          'name_ar' => 'بقوليات وبذور',        'name_ml' => 'പൽസും ഗ്രാമുകളും',     'name_ta' => 'பருப்புகள் மற்றும் பயறுகள்','desc_en' => 'Dal, chickpeas, lentils and gram varieties',                    'desc_ar' => 'عدس وحمص وبقوليات متنوعة', 'image' => 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 9,  'slug' => 'water',           'icon' => '💧', 'name_en' => 'Water',                   'name_ar' => 'مياه',                 'name_ml' => 'വെള്ളം',                 'name_ta' => 'தண்ணீர்',                  'desc_en' => 'Mineral, distilled and flavoured water',                       'desc_ar' => 'مياه معدنية ومقطرة ونكهات', 'image' => 'https://images.unsplash.com/photo-1598871265419-c471c1b43a6c?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 10, 'slug' => 'pickles',         'icon' => '🥒', 'name_en' => 'Pickles & Condiments',    'name_ar' => 'مخللات وتوابل',        'name_ml' => 'അച്ചാറുകളും കണ്ടിമെന്റുകളും','name_ta' => 'ஊறுகாய் மற்றும் சுவைப்பொருட்கள்','desc_en' => 'Mango, lime, mixed pickles and chutneys',                      'desc_ar' => 'مخللات المانجو والليمون والمشكلة', 'image' => 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 11, 'slug' => 'instant',         'icon' => '🍜', 'name_en' => 'Instant & Noodles',       'name_ar' => 'سريع التحضير ونودلز',  'name_ml' => 'ഇൻസ്റ്റന്റും നൂഡിൽസും', 'name_ta' => 'உடனடி மற்றும் நூடுல்ஸ்',   'desc_en' => 'Maggi, instant noodles and ready-to-cook meals',               'desc_ar' => 'ماجي ونودلز جاهزة للطهي', 'image' => 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 12, 'slug' => 'washing',         'icon' => '🧼', 'name_en' => 'Washing & Cleaning',      'name_ar' => 'غسيل وتنظيف',          'name_ml' => 'വാഷിംഗും ക്ലീനിംഗും',  'name_ta' => 'துவைப்பு மற்றும் சுத்தம்', 'desc_en' => 'Detergent, soap, dishwash and cleaners',                        'desc_ar' => 'مسحوق الغسيل والصابون وسائل الأطباق', 'image' => 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 13, 'slug' => 'personal-care',   'icon' => '🧴', 'name_en' => 'Personal Care',           'name_ar' => 'العناية الشخصية',      'name_ml' => 'വ്യക്തിഗത പരിചരണം',     'name_ta' => 'தனிப்பட்ட பராமரிப்பு',    'desc_en' => 'Soap, shampoo, perfume and skincare',                          'desc_ar' => 'صابون وشامبو وعطر ومنتجات العناية', 'image' => 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 14, 'slug' => 'stationary',      'icon' => '📝', 'name_en' => 'Stationery',              'name_ar' => 'قرطاسية',              'name_ml' => 'സ്റ്റേഷനറി',            'name_ta' => 'நிலையம் / எழுதுபொருட்கள்','desc_en' => 'Pens, notebooks, papers and school supplies',                   'desc_ar' => 'أقلام ودفاتر وأوراق ولوازم مدرسية', 'image' => 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 15, 'slug' => 'mats',            'icon' => '🟫', 'name_en' => 'Mats & Home',             'name_ar' => 'حصائر وأدوات المنزل',  'name_ml' => 'മാറ്റുകളും ഹോം ഐറ്റങ്ങളും','name_ta' => 'பாய்கள் மற்றும் வீட்டு பொருட்கள்','desc_en' => 'Prayer mats, floor mats and home essentials',                   'desc_ar' => 'سجاد ومفارش وأدوات منزلية', 'image' => 'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=1920&q=100'],
        ['id' => 16, 'slug' => 'frozen-icecream', 'icon' => '🍦', 'name_en' => 'Frozen & Ice Cream',     'name_ar' => 'مجمدات وآيس كريم',     'name_ml' => 'ഫ്രോസൺ & ഐസ്ക്രീം',    'name_ta' => 'உறைந்த மற்றும் ஐஸ்கிரீம்', 'desc_en' => 'Frozen foods and ice cream tubs',                              'desc_ar' => 'أطعمة مجمدة وآيس كريم', 'image' => 'https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?auto=format&fit=crop&w=1920&q=100'],
    ],

    'products' => [

        // ─── Fruits (id: 1) ───
        ['id' => 1, 'category_id' => 1, 'price' => 12.50, 'unit' => 'kg',   'icon' => '🍎', 'brand' => 'Royal Gala', 'origin' => 'New Zealand', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Royal Gala Apples',      'name_ar' => 'تفاح رويال جالا',       'name_ml' => 'റോയൽ ഗാല ആപ്പിൾ',      'name_ta' => 'ராயல் கலா ஆப்பிள்',      'desc_en' => 'Crisp and sweet Royal Gala apples. Perfect for snacking.',   'desc_ar' => 'تفاح رويال جالا مقرمش وحلو. مثالي للوجبات الخفيفة.'],
        ['id' => 2, 'category_id' => 1, 'price' => 8.75,  'unit' => 'kg',   'icon' => '🍌', 'brand' => 'Dole',       'origin' => 'Ecuador',    'badge' => null, 'image' => 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Cavendish Bananas',       'name_ar' => 'موز كافنديش',           'name_ml' => 'കാവെന്റിഷ് വാഴപ്പഴം',    'name_ta' => 'கேவென்டிஷ் வாழைப்பழம்',   'desc_en' => 'Ripe and creamy Cavendish bananas. Rich in potassium.',       'desc_ar' => 'موز كافنديش ناضج وكريمي. غني بالبوتاسيوم.'],
        ['id' => 3, 'category_id' => 1, 'price' => 24.00, 'unit' => 'box',  'icon' => '🍇', 'brand' => 'Sun World',   'origin' => 'India',      'badge' => null, 'image' => 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Red Globe Grapes',        'name_ar' => 'عنب ريد غلوب',           'name_ml' => 'റെഡ് ഗ്ലോബ് മുന്തിരി',    'name_ta' => 'ரெட் குளோப் திராட்சை',     'desc_en' => 'Plump, seedless red grapes. Sweet and refreshing.',          'desc_ar' => 'عنب أحمر حلو بدون بذور. منعش ولذيذ.'],
        ['id' => 4, 'category_id' => 1, 'price' => 18.00, 'unit' => 'kg',   'icon' => '🥭', 'brand' => 'Al Jazira',   'origin' => 'Egypt',      'badge' => 'local', 'image' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Alphonso Mangoes',        'name_ar' => 'مانجو ألفونسو',          'name_ml' => 'അൽഫോൻസോ മാങ്ങ',          'name_ta' => 'அல்போன்சோ மாம்பழம்',       'desc_en' => 'Golden, juicy Alphonso mangoes. The king of mangoes.',       'desc_ar' => 'مانجو ألفونسو ذهبية وعصيرية. ملك المانجو.'],

        // ─── Vegetables (id: 2) ───
        ['id' => 5, 'category_id' => 2, 'price' => 6.25,  'unit' => 'kg', 'icon' => '🥦', 'brand' => 'Green Valley', 'origin' => 'UAE',   'badge' => 'local', 'image' => 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Fresh Broccoli',    'name_ar' => 'بروكلي طازج',       'name_ml' => 'പുതിയ ബ്രോക്കോളി',     'name_ta' => 'புதிய ப்ரோக்கோலி',    'desc_en' => 'Locally grown broccoli florets. Rich in vitamins.',           'desc_ar' => 'بروكلي مزروع محلياً. غني بالفيتامينات.'],
        ['id' => 6, 'category_id' => 2, 'price' => 4.50,  'unit' => 'kg', 'icon' => '🥕', 'brand' => 'Green Valley', 'origin' => 'UAE',   'badge' => 'local', 'image' => 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Fresh Carrots',     'name_ar' => 'جزر طازج',           'name_ml' => 'പുതിയ കാരറ്റ്',         'name_ta' => 'புதிய கேரட்',          'desc_en' => 'Sweet, crunchy carrots from local farms.',                     'desc_ar' => 'جزر حلو مقرمش من المزارع المحلية.'],
        ['id' => 7, 'category_id' => 2, 'price' => 7.00,  'unit' => 'kg', 'icon' => '🍅', 'brand' => 'Green Valley', 'origin' => 'India',  'badge' => null,    'image' => 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Vine Tomatoes',     'name_ar' => 'طماطم',               'name_ml' => 'തക്കാളി',              'name_ta' => 'தக்காளி',              'desc_en' => 'Rich, flavourful vine tomatoes.',                              'desc_ar' => 'طماطم غنية بالنكهة.'],
        ['id' => 8, 'category_id' => 2, 'price' => 5.50,  'unit' => 'kg', 'icon' => '🧅', 'brand' => 'Green Valley', 'origin' => 'India',  'badge' => null,    'image' => 'https://images.unsplash.com/photo-1618512496961-0f3160a484ba?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Red Onions',       'name_ar' => 'بصل أحمر',            'name_ml' => 'ചുവന്ന ഉള്ളി',          'name_ta' => 'சிவப்பு வெங்காயம்',      'desc_en' => 'Pungent red onions. A kitchen staple.',                        'desc_ar' => 'بصل أحمر حاد. أساسي في كل مطبخ.'],

        // ─── Juices (id: 3) ───
        ['id' => 9,  'category_id' => 3, 'price' => 4.25, 'unit' => '1 L',   'icon' => '🧃', 'brand' => 'Al Rabi',       'origin' => 'UAE', 'badge' => null, 'name_en' => 'Orange Juice',                 'name_ar' => 'عصير برتقال',              'name_ml' => 'ഓറഞ്ച് ജ്യൂസ്',           'name_ta' => 'ஆரஞ்சு சாறு',               'desc_en' => 'Freshly squeezed orange juice. No added sugar.',                  'desc_ar' => 'عصير برتقال طازج. بدون سكر مضاف.', 'image' => 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=800&q=80'],
        ['id' => 10, 'category_id' => 3, 'price' => 8.50, 'unit' => '1 L',   'icon' => '🧃', 'brand' => 'Al Rabi',       'origin' => 'UAE', 'badge' => null, 'name_en' => 'Mango Nectar',                 'name_ar' => 'نكتار مانجو',              'name_ml' => 'മാങ്ങ നെക്റ്റാർ',          'name_ta' => 'மாம்பழம் நெக்டார்',         'desc_en' => 'Rich and thick mango nectar.',                                    'desc_ar' => 'نكتار مانجو غني وسميك.', 'image' => 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80'],
        ['id' => 11, 'category_id' => 3, 'price' => 6.00, 'unit' => '1 L',   'icon' => '🥤', 'brand' => 'Purity',        'origin' => 'UAE', 'badge' => null, 'name_en' => 'Mixed Fruit Juice',            'name_ar' => 'عصير فواكه مشكل',          'name_ml' => 'മിക്സഡ് ഫ്രൂട്ട് ജ്യൂസ്',  'name_ta' => 'கலப்பு பழச்சாறு',            'desc_en' => 'A refreshing blend of tropical fruits.',                           'desc_ar' => 'مزيج منعش من الفواكه الاستوائية.', 'image' => 'https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=800&q=80'],

        // ─── Dairy & Eggs (id: 4) ───
        ['id' => 12, 'category_id' => 4, 'price' => 5.50,  'unit' => '1 L',    'icon' => '🥛', 'brand' => 'Al Ain Dairy', 'origin' => 'UAE',      'badge' => 'local', 'image' => 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Full Cream Milk',          'name_ar' => 'حليب كامل الدسم',        'name_ml' => 'ഫുൾ ക്രീം പാൽ',          'name_ta' => 'முழு கிரீம் பால்',       'desc_en' => 'Fresh full cream milk. Pasteurised.',                       'desc_ar' => 'حليب طازج كامل الدسم. مبستر.'],
        ['id' => 13, 'category_id' => 4, 'price' => 14.50, 'unit' => '12 pcs', 'icon' => '🥚', 'brand' => 'Al Ain Farms', 'origin' => 'UAE',      'badge' => 'local', 'image' => 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Free-Range Eggs',           'name_ar' => 'بيض مراعي حرة',          'name_ml' => 'ഫ്രീ-റേഞ്ച് മുട്ട',        'name_ta' => 'கட்டற்ற மேய்ச்சல் முட்டைகள்', 'desc_en' => 'Farm-fresh free-range eggs.',                                 'desc_ar' => 'بيض طازج من الدجاج الحر.'],
        ['id' => 14, 'category_id' => 4, 'price' => 12.00, 'unit' => '500 g',  'icon' => '🧈', 'brand' => 'Lurpak',       'origin' => 'Denmark',  'badge' => null,    'image' => 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Unsalted Butter',           'name_ar' => 'زبدة غير مملحة',          'name_ml' => 'ഉപ്പില്ലാത്ത ബട്ടർ',       'name_ta' => 'உப்பில்லாத வெண்ணெய்',      'desc_en' => 'Creamy Danish butter from cultured cream.',                   'desc_ar' => 'زبدة دنماركية كريمية.'],
        ['id' => 15, 'category_id' => 4, 'price' => 9.00,  'unit' => '400 g',  'icon' => '🧀', 'brand' => 'Baladna',      'origin' => 'Qatar',    'badge' => null,    'image' => 'https://images.unsplash.com/photo-1558221693-89a565d7ecd8?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Cream Cheese Spread',       'name_ar' => 'جبن كريمي للدهن',         'name_ml' => 'ക്രീം ചീസ് സ്പ്രെഡ്',     'name_ta' => 'கிரீம் சீஸ் ஸ்ப்ரெட்',      'desc_en' => 'Smooth and spreadable cream cheese.',                         'desc_ar' => 'جبن كريمي ناعم قابل للدهن.'],

        // ─── Bakery & Bread (id: 5) ───
        ['id' => 16, 'category_id' => 5, 'price' => 3.75, 'unit' => 'each',   'icon' => '🥖', 'brand' => 'Boulangerie',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1576706626021-3c54f1e1e51a?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Sourdough Loaf',        'name_ar' => 'خبز ساوردو',          'name_ml' => 'സോർഡ്ഡോ റൊട്ടി',        'name_ta' => 'சோர்டோ ரொட்டி',        'desc_en' => 'Artisan sourdough with a crispy crust.',                  'desc_ar' => 'خبز ساوردو حرفي بقشرة مقرمشة.'],
        ['id' => 17, 'category_id' => 5, 'price' => 4.50, 'unit' => 'each',   'icon' => '🍞', 'brand' => 'Boulangerie',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Whole Wheat Bread',    'name_ar' => 'خبز قمح كامل',          'name_ml' => 'മുഴുവൻ ഗോതമ്പ് റൊട്ടി',  'name_ta' => 'முழு கோதுமை ரொட்டி',     'desc_en' => 'Hearty whole wheat loaf, high in fibre.',                  'desc_ar' => 'رغيف قمح كامل غني بالألياف.'],
        ['id' => 18, 'category_id' => 5, 'price' => 2.50, 'unit' => 'each',   'icon' => '🥐', 'brand' => 'Boulangerie',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Butter Croissant',     'name_ar' => 'كرواسون بالزبدة',       'name_ml' => 'ബട്ടർ ക്രോയിസന്റ്',      'name_ta' => 'வெண்ணெய் குரோஸான்',       'desc_en' => 'Flaky, golden-baked butter croissant. Fresh daily.',        'desc_ar' => 'كرواسون بالزبدة هش وذهبي. طازج يومياً.'],
        ['id' => 19, 'category_id' => 5, 'price' => 6.00, 'unit' => '200 g',  'icon' => '🥯', 'brand' => 'Boulangerie',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Bread Rolls (4 pcs)',  'name_ar' => 'أرغفة صغيرة',           'name_ml' => 'ബ്രഡ് റോൾസ്',            'name_ta' => 'பிரெட் ரோல்கள்',           'desc_en' => 'Soft dinner rolls, perfect with curries.',                   'desc_ar' => 'أرغفة عشاء طرية.'],

        // ─── Snacks & Biscuits (id: 6) ───
        ['id' => 20, 'category_id' => 6, 'price' => 7.00,  'unit' => '150 g', 'icon' => '🍪', 'brand' => 'McVitie\'s',      'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Digestive Biscuits',       'name_ar' => 'بسكويت دايجستيف',        'name_ml' => 'ഡൈജസ്റ്റീവ് ബിസ്ക്കറ്റ്', 'name_ta' => 'டைஜெஸ்டிவ் பிஸ்கட்', 'desc_en' => 'Classic wheat biscuits. Perfect with tea.',                 'desc_ar' => 'بسكويت قمح كلاسيكي. مثالي مع الشاي.'],
        ['id' => 21, 'category_id' => 6, 'price' => 12.00, 'unit' => '100 g', 'icon' => '🍫', 'brand' => 'Lindt',            'origin' => 'Switzerland', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Dark Chocolate 70%',         'name_ar' => 'شوكولاتة داكنة 70٪',      'name_ml' => 'ഡാർക്ക് ചോക്ലേറ്റ് 70%',  'name_ta' => 'டார்க் சாக்லேட் 70%',   'desc_en' => 'Rich Swiss dark chocolate.',                                   'desc_ar' => 'شوكولاتة سويسرية داكنة غنية.'],
        ['id' => 22, 'category_id' => 6, 'price' => 5.00,  'unit' => '200 g', 'icon' => '🥔', 'brand' => 'Lay\'s',           'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Potato Chips - Salted',     'name_ar' => 'رقائق بطاطس مملحة',       'name_ml' => 'ഉപ്പിട്ട പൊട്ടാറ്റോ ചിപ്സ്', 'name_ta' => 'உப்பிட்ட பீங்கான் சிப்ஸ்', 'desc_en' => 'Crunchy salted potato chips.',                                  'desc_ar' => 'رقائق بطاطس مقرمشة مملحة.'],
        ['id' => 23, 'category_id' => 6, 'price' => 8.00,  'unit' => '120 g', 'icon' => '🍫', 'brand' => 'Kinder',           'origin' => 'Italy', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1586400928533-da0dbdca07fb?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Kinder Chocolate Bar',       'name_ar' => 'شوكولاتة كيندر',          'name_ml' => 'കിൻഡർ ചോക്ലേറ്റ് ബാർ',   'name_ta' => 'கிண்டர் சாக்லேட் பார்',  'desc_en' => 'Creamy milk chocolate with a milky filling.',                   'desc_ar' => 'شوكولاتة حليب كريمية بحشوة حليبية.'],

        // ─── Rice (id: 7) ───
        ['id' => 24, 'category_id' => 7, 'price' => 8.00,  'unit' => '1 kg',  'icon' => '🍚', 'brand' => 'India Gate',    'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Basmati Rice',          'name_ar' => 'أرز بسمتي',            'name_ml' => 'ബാസ്മതി അരി',          'name_ta' => 'பாஸ்மதி அரிசி',        'desc_en' => 'Premium long-grain basmati rice. Aromatic and fluffy.',          'desc_ar' => 'أرز بسمتي ممتاز طويل الحبة. عطري وهش.'],
        ['id' => 25, 'category_id' => 7, 'price' => 6.50,  'unit' => '1 kg',  'icon' => '🍚', 'brand' => 'Double Horse',  'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Sona Masoori Rice',     'name_ar' => 'أرز سونا ماسوري',        'name_ml' => 'സോണ മസൂരി അരി',        'name_ta' => 'சோனா மசூரி அரிசி',       'desc_en' => 'Soft, medium-grain everyday rice.',                              'desc_ar' => 'أرز متوسط الحبة لكل يوم.'],
        ['id' => 26, 'category_id' => 7, 'price' => 11.00, 'unit' => '1 kg',  'icon' => '🌾', 'brand' => 'Kerala',        'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Jeerakasala Rice',     'name_ar' => 'أرز جيراكاسالا',         'name_ml' => 'ജീരകശാല അരി',           'name_ta' => 'ஜீரகசால அரிசி',            'desc_en' => 'Fragrant short-grain rice for biryani.',                        'desc_ar' => 'أرز قصير معطر للبرياني.'],
        ['id' => 27, 'category_id' => 7, 'price' => 9.50,  'unit' => '1 kg',  'icon' => '🍚', 'brand' => 'Rose',          'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1614456382970-5e3d203f2850?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Matta (Red) Rice',     'name_ar' => 'أرز أحمر',              'name_ml' => 'മട്ട അരി',                'name_ta' => 'மாட்டை (சிவப்பு) அரிசி',    'desc_en' => 'Nutty red parboiled rice from Kerala.',                         'desc_ar' => 'أرز أحمر من كيرالا.'],

        // ─── Pulses & Grams (id: 8) ───
        ['id' => 28, 'category_id' => 8, 'price' => 5.00,  'unit' => '1 kg', 'icon' => '🟡', 'brand' => 'Tata',         'origin' => 'India', 'badge' => null, 'name_en' => 'Toor Dal (Pigeon Pea)',   'name_ar' => 'دال تور',               'name_ml' => 'തുവര ദാല്',            'name_ta' => 'துவரம் பருப்பு',          'desc_en' => 'Essential dal for sambar and curries.',                          'desc_ar' => 'دال أساسي للسامبار والكاري.', 'image' => 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80'],
        ['id' => 29, 'category_id' => 8, 'price' => 6.00,  'unit' => '1 kg', 'icon' => '🔴', 'brand' => 'Tata',         'origin' => 'India', 'badge' => null, 'name_en' => 'Red Chana (Chickpeas)',   'name_ar' => 'حمص أحمر',              'name_ml' => 'കടുക ചണ',                'name_ta' => 'கொண்டைக்கடலை',            'desc_en' => 'Firm chickpeas for curries and salads.',                        'desc_ar' => 'حمص صلب للكاري والسلطات.', 'image' => 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80'],
        ['id' => 30, 'category_id' => 8, 'price' => 7.50,  'unit' => '1 kg', 'icon' => '🟢', 'brand' => 'Organic',      'origin' => 'India', 'badge' => 'organic', 'name_en' => 'Green Moong Dal',          'name_ar' => 'دال مونج أخضر',         'name_ml' => 'പച്ച മൂംഗ് ദാൽ',         'name_ta' => 'பச்சை மூங் பருப்பு',        'desc_en' => 'Easy-to-digest split mung beans.',                              'desc_ar' => 'عدس مونج سهل الهضم.', 'image' => 'https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?auto=format&fit=crop&w=800&q=80'],
        ['id' => 31, 'category_id' => 8, 'price' => 5.50,  'unit' => '1 kg', 'icon' => '⚪', 'brand' => 'Local',        'origin' => 'UAE',   'badge' => 'local', 'name_en' => 'Urad Dal (White)',         'name_ar' => 'دال أوراد أبيض',         'name_ml' => 'വെളുത്ത ഉഴുന്ന്',          'name_ta' => 'உளுந்து பருப்பு',            'desc_en' => 'Key ingredient for dosa and idli batter.',                      'desc_ar' => 'مكون أساسي لعجينة الدوسا والأيدلي.', 'image' => 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=800&q=80'],

        // ─── Water (id: 9) ───
        ['id' => 32, 'category_id' => 9, 'price' => 2.00,  'unit' => '1.5 L',  'icon' => '💧', 'brand' => 'Al Ain Water', 'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Still Water',        'name_ar' => 'مياه معدنية',        'name_ml' => 'സ്റ്റിൽ വാട്ടർ',        'name_ta' => 'நிலை நீர்',            'desc_en' => 'Pure natural mineral water.',                              'desc_ar' => 'مياه معدنية طبيعية نقية.'],
        ['id' => 33, 'category_id' => 9, 'price' => 14.00, 'unit' => '750 ml', 'icon' => '🍾', 'brand' => 'Pellegrino',    'origin' => 'Italy', 'badge' => 'premium', 'image' => 'https://images.unsplash.com/photo-1523362628745-0c100fc988a6?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Sparkling Water', 'name_ar' => 'مياه فوارة',          'name_ml' => 'സ്പാർക്ലിംഗ് വാട്ടർ',   'name_ta' => 'ஸ்பார்க்லிங் நீர்',      'desc_en' => 'Italian sparkling mineral water.',                           'desc_ar' => 'مياه معدنية إيطالية فوارة.'],
        ['id' => 34, 'category_id' => 9, 'price' => 3.00,  'unit' => '500 ml', 'icon' => '💧', 'brand' => 'Masafi',        'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1560028154-3c63e5b39b9c?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Distilled Water',   'name_ar' => 'مياه مقطرة',          'name_ml' => 'ഡിസ്റ്റിൽഡ് വാട്ടർ',       'name_ta' => 'வடிகட்டிய நீர்',         'desc_en' => 'Pure distilled water for home use.',                         'desc_ar' => 'مياه مقطرة نقية للاستخدام المنزلي.'],

        // ─── Pickles & Condiments (id: 10) ───
        ['id' => 35, 'category_id' => 10, 'price' => 4.50, 'unit' => '400 g', 'icon' => '🥭', 'brand' => 'Priya',    'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1585435465945-bef5a93f8849?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Mango Pickle',        'name_ar' => 'مخلل مانجو',        'name_ml' => 'മാങ്ങ അച്ചാർ',        'name_ta' => 'மாங்காய் ஊறுகாய்',     'desc_en' => 'Tangy and spicy mango pickle.',                        'desc_ar' => 'مخلل مانجو حامض وحار.'],
        ['id' => 36, 'category_id' => 10, 'price' => 4.00, 'unit' => '400 g', 'icon' => '🍋', 'brand' => 'Priya',    'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Lime Pickle',        'name_ar' => 'مخلل ليمون',         'name_ml' => 'നാരങ്ങ അച്ചാർ',        'name_ta' => 'எலுமிச்சை ஊறுகாய்',    'desc_en' => 'Sharp and salty lime pickle.',                          'desc_ar' => 'مخلل ليمون حاد ومالح.'],
        ['id' => 37, 'category_id' => 10, 'price' => 6.50, 'unit' => '300 g', 'icon' => '🥒', 'brand' => 'Mother',   'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Mixed Veg Pickle',   'name_ar' => 'مخلل خضار مشكل',      'name_ml' => 'മിക്സഡ് വെജ് അച്ചാർ', 'name_ta' => 'கலவை காய்கறி ஊறுகாய்', 'desc_en' => 'A medley of vegetables in spicy brine.',                 'desc_ar' => 'مزيج من الخضار في محلول حار.'],

        // ─── Instant & Noodles (id: 11) ───
        ['id' => 38, 'category_id' => 11, 'price' => 1.50, 'unit' => 'pack', 'icon' => '🍜', 'brand' => 'Maggi',    'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1628610688436-e635552020fc?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Maggi 2-Minute Noodles', 'name_ar' => 'نودلز ماجي',     'name_ml' => 'മഗ്ഗി നൂഡിൽസ്',      'name_ta' => 'மாக்கி நூடுல்ஸ்',        'desc_en' => 'Classic masala instant noodles.',                       'desc_ar' => 'نودلز سريعة بالمسالا.'],
        ['id' => 39, 'category_id' => 11, 'price' => 2.00, 'unit' => 'pack', 'icon' => '🍜', 'brand' => 'Maggi',    'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1664337873053-840ea51d271d?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Maggi Chicken Noodles', 'name_ar' => 'نودلز دجاج ماجي', 'name_ml' => 'മഗ്ഗി ചിക്കൻ നൂഡിൽസ്', 'name_ta' => 'மாக்கி சிக்கன் நூடுல்ஸ்', 'desc_en' => 'Savoury chicken-flavour instant noodles.',              'desc_ar' => 'نودلز سريعة بنكهة الدجاج.'],
        ['id' => 40, 'category_id' => 11, 'price' => 3.50, 'unit' => 'cup',  'icon' => '🍲', 'brand' => 'Knorr',    'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Cup Soup - Veg',        'name_ar' => 'شوربة كوب خضار',     'name_ml' => 'വെജ് കപ്പ് സൂപ്പ്',     'name_ta' => 'காய்கறி கப் சூப்',       'desc_en' => 'Warm ready-to-cook cup soup.',                          'desc_ar' => 'شوربة جاهزة على الطهي.'],

        // ─── Washing & Cleaning (id: 12) ───
        ['id' => 41, 'category_id' => 12, 'price' => 12.00, 'unit' => '1 L',   'icon' => '🧴', 'brand' => 'Fairy',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Liquid Dish Soap',     'name_ar' => 'سائل غسيل الأطباق', 'name_ml' => 'ഡിഷ് വാഷ് ലിക്വിഡ്',  'name_ta' => 'டிஷ் வாஷ் திரவம்',      'desc_en' => 'Concentrated dish soap, lemon fresh.',                'desc_ar' => 'سائل غسيل أطباق مركز.'],
        ['id' => 42, 'category_id' => 12, 'price' => 18.00, 'unit' => '3 kg',  'icon' => '🧼', 'brand' => 'Tide',    'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Tide Detergent',       'name_ar' => 'مسحوق تايد',         'name_ml' => 'ടൈഡ് ഡിറ്റർജന്റ്',      'name_ta' => 'டைட் டிடர்ஜன்ட்',         'desc_en' => 'Powerful laundry detergent for all fabrics.',          'desc_ar' => 'مسحوق غسيل قوي لكل الأقمشة.'],
        ['id' => 43, 'category_id' => 12, 'price' => 15.00, 'unit' => '2 L',   'icon' => '🧹', 'brand' => 'Dettol',  'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1563456160-6ef088d53f31?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Multi-Purpose Cleaner', 'name_ar' => 'منظف متعدد الأغراض','name_ml' => 'മൾട്ടി-പർപ്പസ് ക്ലീനർ', 'name_ta' => 'பல்நோக்க சுத்தப்படுத்தி', 'desc_en' => 'Antibacterial multi-purpose cleaner.',                 'desc_ar' => 'منظف متعدد الأغراض مضاد للبكتيريا.'],

        // ─── Personal Care (id: 13) ───
        ['id' => 44, 'category_id' => 13, 'price' => 18.00, 'unit' => '200 ml', 'icon' => '🧴', 'brand' => 'L\'Oréal Paris', 'origin' => 'France', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Repair Shampoo',   'name_ar' => 'شامبو مغذي',      'name_ml' => 'റിപ്പയർ ഷാംപൂ',   'name_ta' => 'சரம் ஷாம்பு',        'desc_en' => 'Repairing shampoo with ceramide.',                    'desc_ar' => 'شامبو مرمم بالسيراميد.'],
        ['id' => 45, 'category_id' => 13, 'price' => 8.00,  'unit' => '100 ml', 'icon' => '🪥', 'brand' => 'Colgate',        'origin' => 'UAE',   'badge' => null, 'image' => 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Whitening Toothpaste', 'name_ar' => 'معجون أسنان مبيض', 'name_ml' => 'വൈറ്റ്നിംഗ് ടൂത്ത്പേസ്റ്റ്','name_ta' => 'வெண்மையாக்கும் பற்பசை', 'desc_en' => 'Advanced whitening toothpaste.',                       'desc_ar' => 'معجون أسنان مبيض متقدم.'],
        ['id' => 46, 'category_id' => 13, 'price' => 35.00, 'unit' => '100 ml', 'icon' => '🌸', 'brand' => 'Junaid',         'origin' => 'UAE',   'badge' => null, 'image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Oud Perfume',       'name_ar' => 'عطر عود',          'name_ml' => 'ഊദ് പെർഫ്യൂം',        'name_ta' => 'ஊத் வாசனை திரவியம்',   'desc_en' => 'Rich Middle-Eastern oud attar.',                       'desc_ar' => 'عطر عود شرق أوسطي غني.'],
        ['id' => 47, 'category_id' => 13, 'price' => 4.50,  'unit' => '100 g',  'icon' => '🧼', 'brand' => 'Lifebuoy',       'origin' => 'UAE',   'badge' => null, 'image' => 'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Bathing Soap',     'name_ar' => 'صابون استحمام',     'name_ml' => 'ബാത്ത് സോപ്പ്',        'name_ta' => 'குளியல் சோப்',           'desc_en' => 'Germ-protection bathing soap.',                        'desc_ar' => 'صابون استحمام وقائي.'],

        // ─── Stationery (id: 14) ───
        ['id' => 48, 'category_id' => 14, 'price' => 3.00, 'unit' => 'pack', 'icon' => '🖊️', 'brand' => 'Parker',  'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Ballpoint Pens (10)',   'name_ar' => 'أقلام حبر (10)',     'name_ml' => 'ബോൾപോയിന്റ് പേനകൾ', 'name_ta' => 'பால்பாயிண்ட் பேனாக்கள்', 'desc_en' => 'Smooth-writing ballpoint pens.',                    'desc_ar' => 'أقلام حبر سلسة.'],
        ['id' => 49, 'category_id' => 14, 'price' => 5.00, 'unit' => 'each', 'icon' => '📒', 'brand' => 'Classmate', 'origin' => 'India', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Notebook A4',        'name_ar' => 'دفتر A4',            'name_ml' => 'നോട്ട്ബുക്ക് A4',       'name_ta' => 'நோட்புக் A4',            'desc_en' => '200-page ruled A4 notebook.',                        'desc_ar' => 'دفتر A4 مق rul 200 صفحة.'],

        // ─── Mats & Home (id: 15) ───
        ['id' => 50, 'category_id' => 15, 'price' => 25.00, 'unit' => 'each', 'icon' => '🟫', 'brand' => 'Home',  'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Prayer Mat',        'name_ar' => 'سجادة صلاة',       'name_ml' => 'പ്രാർത്ഥന മാറ്റ്',  'name_ta' => 'வழிபாட்டு பாய்',       'desc_en' => 'Soft polypropylene prayer mat.',                  'desc_ar' => 'سجادة صلاة ناعمة.'],
        ['id' => 51, 'category_id' => 15, 'price' => 40.00, 'unit' => 'each', 'icon' => '🟫', 'brand' => 'Home',  'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Floor Mat (Large)',  'name_ar' => 'سجادة أرضية',       'name_ml' => 'ഫ്ലോർ മാറ്റ്',         'name_ta' => 'தரை பாய்',               'desc_en' => 'Large woven floor mat for the home.',               'desc_ar' => 'سجادة أرضية كبيرة.'],

        // ─── Frozen & Ice Cream (id: 16) ───
        ['id' => 52, 'category_id' => 16, 'price' => 22.00, 'unit' => '500 g', 'icon' => '🍦', 'brand' => 'Al Rabi', 'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Vanilla Ice Cream',   'name_ar' => 'آيس كريم فانيليا',  'name_ml' => 'വെനില ഐസ്ക്രീം',     'name_ta' => 'வெண்ணிலா ஐஸ்கிரீம்',    'desc_en' => 'Creamy vanilla ice cream.',                          'desc_ar' => 'آيس كريم فانيليا كريمي.'],
        ['id' => 53, 'category_id' => 16, 'price' => 15.00, 'unit' => '1 kg',  'icon' => '🥟', 'brand' => 'Local',   'origin' => 'UAE', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1606521439237-59be68802713?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Veg Spring Rolls',    'name_ar' => 'سمبوسة خضار',        'name_ml' => 'വെജ് സ്പ്രിംഗ് റോൾ',   'name_ta' => 'காய்கறி ஸ்பிரிங் ரோல்',  'desc_en' => 'Crispy vegetable spring rolls.',                     'desc_ar' => 'سمبوسة خضار مقرمشة.'],
        ['id' => 54, 'category_id' => 16, 'price' => 18.00, 'unit' => '750 g', 'icon' => '🍕', 'brand' => 'Oetker',  'origin' => 'Germany', 'badge' => null, 'image' => 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80', 'name_en' => 'Margherita Pizza', 'name_ar' => 'بيتزا مارغريتا',     'name_ml' => 'മാർഗരീറ്റ പിസ്സ',       'name_ta' => 'மார்கெரிட்டா பீஸ்ஸா',     'desc_en' => 'Stone-baked Margherita pizza.',                      'desc_ar' => 'بيتزا مارغريتا مخبوزة على الحجر.'],

        // ─── Bulk Orders (id: 17) — on request ───
    ],

    'offers' => [
        ['product_id' => 4,  'percent' => 20, 'valid_until' => '2026-08-15', 'label_en' => 'Mango Madness',      'label_ar' => 'جنون المانجو'],
        ['product_id' => 13, 'percent' => 25, 'valid_until' => '2026-07-31', 'label_en' => 'Egg-cellent Deal',  'label_ar' => 'عرض البيض الرائع'],
        ['product_id' => 18, 'percent' => 10, 'valid_until' => '2026-08-10', 'label_en' => 'Bakery Bites',      'label_ar' => 'لقيمات المخبوزات'],
        ['product_id' => 24, 'percent' => 15, 'valid_until' => '2026-08-20', 'label_en' => 'Rice Festival',     'label_ar' => 'مهرجان الأرز'],
        ['product_id' => 28, 'percent' => 15, 'valid_until' => '2026-08-05', 'label_en' => 'Dal Daily',         'label_ar' => 'دال يومي'],
        ['product_id' => 33, 'percent' => 25, 'valid_until' => '2026-08-15', 'label_en' => 'Hydrate Sale',     'label_ar' => 'عرض الترطيب'],
        ['product_id' => 42, 'percent' => 20, 'valid_until' => '2026-08-10', 'label_en' => 'Clean Home',       'label_ar' => 'بيت نظيف'],
        ['product_id' => 52, 'percent' => 30, 'valid_until' => '2026-07-28', 'label_en' => 'Cool Down',        'label_ar' => 'تبرد'],
        ['product_id' => 22, 'percent' => 15, 'valid_until' => '2026-08-20', 'label_en' => 'Chocolate Crave',  'label_ar' => 'شوق الشوكولاتة'],
        ['product_id' => 38, 'percent' => 20, 'valid_until' => '2026-08-01', 'label_en' => 'Instant Meals',    'label_ar' => 'وجبات سريعة'],
        ['product_id' => 46, 'percent' => 25, 'valid_until' => '2026-08-15', 'label_en' => 'Oud Special',      'label_ar' => 'عرض العود'],
        ['product_id' => 50, 'percent' => 15, 'valid_until' => '2026-08-20', 'label_en' => 'Prayer Essentials','label_ar' => 'أساسيات الصلاة'],
    ],

    'store_locations' => [
        [
            'id' => 1,
            'name' => 'Bab al Awir — Al Awir (Headquarters)',
            'name_ar' => 'باب العوير — العوير (المقر الرئيسي)',
            'address' => 'Al Awir Road, Dubai, United Arab Emirates',
            'address_ar' => 'شارع العوير، دبي، الإمارات العربية المتحدة',
            'phone' => '+971 4 000 0001',
            'email' => 'al.awir@babalawir.ae',
            'hours' => [
                'saturday_wednesday' => '7:00 AM – 11:00 PM',
                'thursday' => '7:00 AM – 12:00 AM',
                'friday' => '2:00 PM – 11:00 PM',
            ],
            'services' => ['Free Parking', 'Home Delivery', 'In-store Bakery', 'Fresh Butcher'],
            'coordinates' => ['lat' => 25.2048, 'lng' => 55.2708],
        ],
        [
            'id' => 2,
            'name' => 'Bab al Awir — Dubai Marina',
            'name_ar' => 'باب العوير — مرسى دبي',
            'address' => 'Dubai Marina Walk, Dubai, United Arab Emirates',
            'address_ar' => 'مرسى دبي، دبي، الإمارات العربية المتحدة',
            'phone' => '+971 4 000 0002',
            'email' => 'marina@babalawir.ae',
            'hours' => [
                'saturday_wednesday' => '8:00 AM – 10:00 PM',
                'thursday' => '8:00 AM – 11:00 PM',
                'friday' => '2:00 PM – 10:00 PM',
            ],
            'services' => ['Valet Parking', 'Home Delivery', 'Organic Section', 'Café'],
            'coordinates' => ['lat' => 25.0803, 'lng' => 55.1403],
        ],
        [
            'id' => 3,
            'name' => 'Bab al Awir — Abu Dhabi',
            'name_ar' => 'باب العوير — أبوظبي',
            'address' => 'Al Reem Island, Abu Dhabi, United Arab Emirates',
            'address_ar' => 'جزيرة الريم، أبوظبي، الإمارات العربية المتحدة',
            'phone' => '+971 4 000 0003',
            'email' => 'abudhabi@babalawir.ae',
            'hours' => [
                'saturday_wednesday' => '7:00 AM – 11:00 PM',
                'thursday' => '7:00 AM – 12:00 AM',
                'friday' => '2:00 PM – 11:00 PM',
            ],
            'services' => ['Free Parking', 'Home Delivery', 'Pharmacy', 'Hot Food Counter'],
            'coordinates' => ['lat' => 24.4539, 'lng' => 54.3953],
        ],
        [
            'id' => 4,
            'name' => 'Bab al Awir — Riyadh',
            'name_ar' => 'باب العوير — الرياض',
            'address' => 'Al Olaya District, Riyadh, Saudi Arabia',
            'address_ar' => 'حي العليا، الرياض، المملكة العربية السعودية',
            'phone' => '+966 11 000 0001',
            'email' => 'riyadh@babalawir.ae',
            'hours' => [
                'saturday_wednesday' => '7:00 AM – 11:00 PM',
                'thursday' => '7:00 AM – 12:00 AM',
                'friday' => '1:30 PM – 11:00 PM',
            ],
            'services' => ['Free Parking', 'Home Delivery', 'International Foods', 'Grill Station'],
            'coordinates' => ['lat' => 24.7136, 'lng' => 46.6753],
        ],
    ],

    'delivery_options' => [
        [
            'method' => 'standard',
            'label_en' => 'Standard Delivery',
            'label_ar' => 'توصيل قياسي',
            'desc_en' => 'Delivered within 2–3 business days',
            'desc_ar' => 'التوصيل خلال 2–3 أيام عمل',
            'fee' => 15.00,
            'free_above' => 100.00,
            'estimated_days' => '2–3',
        ],
        [
            'method' => 'express',
            'label_en' => 'Express Delivery',
            'label_ar' => 'توصيل سريع',
            'desc_en' => 'Same-day delivery within 4 hours',
            'desc_ar' => 'توصيل في نفس اليوم خلال 4 ساعات',
            'fee' => 25.00,
            'free_above' => null,
            'estimated_days' => 'Same day',
        ],
        [
            'method' => 'scheduled',
            'label_en' => 'Scheduled Delivery',
            'label_ar' => 'توصيل مجدول',
            'desc_en' => 'Pick your preferred time slot (free for orders over 150 AED)',
            'desc_ar' => 'اختر الوقت المناسب لك (مجاني للطلبات فوق 150 درهماً)',
            'fee' => 10.00,
            'free_above' => 150.00,
            'estimated_days' => 'Scheduled',
        ],
    ],

    'testimonials' => [
        [
            'id' => 1,
            'name_en' => 'Sarah M.',
            'name_ar' => 'سارة م.',
            'role_en' => 'Loyal Customer',
            'role_ar' => 'عميل مخلص',
            'rating' => 5,
            'text_en' => 'The freshest produce I have found in Dubai. The delivery is always on time and the staff are incredibly friendly.',
            'text_ar' => 'أطازج منتجات وجدتها في دبي. التوصيل دائماً في الوقت المحدد والموظفون ودودون بشكل لا يصدق.',
            'avatar' => 'SM',
        ],
        [
            'id' => 2,
            'name_en' => 'Ahmed K.',
            'name_ar' => 'أحمد ك.',
            'role_en' => 'Business Owner',
            'role_ar' => 'صاحب عمل',
            'rating' => 5,
            'text_en' => 'I order in bulk for my restaurant every week. Their seafood section is unmatched — always fresh, always reliable.',
            'text_ar' => 'أطلب بالجملة لمطعمي كل أسبوع. قسم المأكولات البحرية لا مثيل له — دائماً طازج وموثوق.',
            'avatar' => 'AK',
        ],
        [
            'id' => 3,
            'name_en' => 'Priya S.',
            'name_ar' => 'بريا س.',
            'role_en' => 'Working Mother',
            'role_ar' => 'أم عاملة',
            'rating' => 4,
            'text_en' => 'The scheduled delivery is a lifesaver. I pick my time slot and groceries arrive right on time. Highly recommend!',
            'text_ar' => 'التوصيل المجدول منقذ للحياة. أختار الوقت المناسب وتوصل البقالة في الوقت المحدد. أنصح بشدة!',
            'avatar' => 'PS',
        ],
        [
            'id' => 4,
            'name_en' => 'Omar H.',
            'name_ar' => 'عمر ح.',
            'role_en' => 'Fitness Coach',
            'role_ar' => 'مدرب لياقة',
            'rating' => 5,
            'text_en' => 'Their organic section is amazing. I can always find fresh kale, chia seeds, and protein options for my clients.',
            'text_ar' => 'قسم المنتجات العضوية رائع. أجد دائماً كالي طازج وبذور شيا وخيارات بروتين لعملائي.',
            'avatar' => 'OH',
        ],
        [
            'id' => 5,
            'name_en' => 'Fatima R.',
            'name_ar' => 'فاطمة ر.',
            'role_en' => 'Homemaker',
            'role_ar' => 'ربة منزل',
            'rating' => 5,
            'text_en' => 'The prices are fair and the quality is consistent. My family loves the bakery section — their sourdough is the best!',
            'text_ar' => 'الأسعار منصفة والجودة متسقة. عائلتي تحب قسم المخبوزات — خبز الساوردو هو الأفضل!',
            'avatar' => 'FR',
        ],
        [
            'id' => 6,
            'name_en' => 'David L.',
            'name_ar' => 'ديفيد ل.',
            'role_en' => 'Expat in Dubai',
            'role_ar' => 'مقي في دبي',
            'rating' => 4,
            'text_en' => 'Great variety of international products. As an expat, I appreciate finding ingredients from my home country here.',
            'text_ar' => 'تشكيلة رائعة من المنتجات الدولية. كمقيم، أقدر العثور على مكونات من بلدي هنا.',
            'avatar' => 'DL',
        ],
    ],

    'faq' => [
        [
            'id' => 1,
            'question_en' => 'What are your delivery hours?',
            'question_ar' => 'ما هي ساعات التوصيل؟',
            'answer_en' => 'We deliver from 8:00 AM to 10:00 PM every day, including weekends. Express delivery is available within 4 hours of placing your order.',
            'answer_ar' => 'نوصّل من الساعة 8:00 صباحاً حتى 10:00 مساءً كل يوم، بما في ذلك عطلات نهاية الأسبوع. التوصيل السريع متاح خلال 4 ساعات من تقديم الطلب.',
        ],
        [
            'id' => 2,
            'question_en' => 'Is there a minimum order amount?',
            'question_ar' => 'هل هناك حد أدنى لمبلغ الطلب؟',
            'answer_en' => 'There is no minimum order. Standard delivery is 15 AED, but it is free for orders above 100 AED.',
            'answer_ar' => 'لا يوجد حد أدنى للطلب. التوصيل القياسي 15 درهماً، لكنه مجاني للطلبات فوق 100 درهم.',
        ],
        [
            'id' => 3,
            'question_en' => 'Do you offer organic products?',
            'question_ar' => 'هل تقدمون منتجات عضوية؟',
            'answer_en' => 'Yes! We have a dedicated Organic & Health section with certified organic produce, superfoods, and natural supplements.',
            'answer_ar' => 'نعم! لدينا قسم مخصص للمنتجات العضوية والصحية يحتوي على منتجات عضوية معتمدة وأطعمة فائقة ومكملات طبيعية.',
        ],
        [
            'id' => 4,
            'question_en' => 'Can I return or exchange items?',
            'question_ar' => 'هل يمكنني إرجاع أو استبدال المنتجات؟',
            'answer_en' => 'Yes, you can return any fresh product within 24 hours of delivery for a full refund or exchange. Processed items can be returned within 7 days.',
            'answer_ar' => 'نعم، يمكنك إرجاع أي منتج طازج خلال 24 ساعة من التوصيل للحصول على استرداد كامل أو استبدال. يمكن إرجاع المنتجات المعالجة خلال 7 أيام.',
        ],
        [
            'id' => 5,
            'question_en' => 'How does the loyalty program work?',
            'question_ar' => 'كيف يعمل برنامج الولاء؟',
            'answer_en' => 'Earn 1 point for every 1 AED spent. Bronze (0–500 pts), Silver (500–1000 pts), Gold (1000–2500 pts), Platinum (2500+ pts). Each tier unlocks exclusive discounts.',
            'answer_ar' => 'احصل على نقطة واحدة لكل درهم تنفقه. برونزي (0-500 نقطة)، فضي (500-1000 نقطة)، ذهبي (1000-2500 نقطة)، بلاتيني (2500+ نقطة). كل مستوى يفتح خصومات حصرية.',
        ],
        [
            'id' => 6,
            'question_en' => 'Do you accept digital payments?',
            'question_ar' => 'هل تقبلون المدفوعات الرقمية؟',
            'answer_en' => 'We accept all major credit/debit cards, Apple Pay, Google Pay, and cash on delivery.',
            'answer_ar' => 'نقبل جميع بطاقات الائتمان/الخصم الرئيسية، وأبل باي، وجوجل باي، والدفع نقداً عند التوصيل.',
        ],
        [
            'id' => 7,
            'question_en' => 'Where are your stores located?',
            'question_ar' => 'أين تقع فروعكم؟',
            'answer_en' => 'We have 4 stores: Al Awir (HQ), Dubai Marina, Abu Dhabi (Al Reem Island), and Riyadh (Al Olaya). Each store offers unique services.',
            'answer_ar' => 'لدينا 4 فروع: العوير (المقر الرئيسي)، مرسى دبي، أبوظبي (جزيرة الريم)، والرياض (العليا). كل فرع يقدم خدمات فريدة.',
        ],
        [
            'id' => 8,
            'question_en' => 'Can I schedule a delivery for a specific time?',
            'question_ar' => 'هل يمكنني جدولة التوصيل لوقت محدد؟',
            'answer_en' => 'Yes, our Scheduled Delivery option lets you choose a preferred time slot. It costs 10 AED but is free for orders above 150 AED.',
            'answer_ar' => 'نعم، خيار التوصيل المجدول يتيح لك اختيار الوقت المفضل. التكلفة 10 دراهم لكنه مجاني للطلبات فوق 150 درهم.',
        ],
    ],

    'team_members' => [
        [
            'id' => 1,
            'name_en' => 'Khalid Al Maktoum',
            'name_ar' => 'خالد المكتوم',
            'role_en' => 'Founder & CEO',
            'role_ar' => 'المؤسس والرئيس التنفيذي',
            'bio_en' => 'Started Bab al Awir in 2018 with a vision to bring fresh, quality groceries to every Gulf household.',
            'bio_ar' => 'أسس باب العوير في 2018 برؤية لتقديم بقالة طازجة وعالية الجودة لكل أسرة خليجية.',
            'avatar' => 'KM',
        ],
        [
            'id' => 2,
            'name_en' => 'Nadia Farouk',
            'name_ar' => 'نادية فاروق',
            'role_en' => 'Head of Operations',
            'role_ar' => 'رئيسة العمليات',
            'bio_en' => 'Oversees supply chain and logistics across all 4 stores. 15 years of retail experience.',
            'bio_ar' => 'تشرف على سلسلة التوريد واللوجستيات عبر جميع الفروع الأربعة. 15 عاماً من الخبرة في التجزئة.',
            'avatar' => 'NF',
        ],
        [
            'id' => 3,
            'name_en' => 'Raj Mehta',
            'name_ar' => 'راج ميهتا',
            'role_en' => 'Quality Assurance Director',
            'role_ar' => 'مدير ضمان الجودة',
            'bio_en' => 'Ensures every product meets our strict freshness and safety standards before reaching store shelves.',
            'bio_ar' => 'يضمن أن كل منتج يلبي معايير النضارة والسلامة الصارمة قبل وصوله إلى أرفف المتجر.',
            'avatar' => 'RM',
        ],
        [
            'id' => 4,
            'name_en' => 'Sara Al Hashimi',
            'name_ar' => 'سارة الهاشمي',
            'role_en' => 'Customer Experience Lead',
            'role_ar' => 'رئيسة تجربة العملاء',
            'bio_en' => 'Leads our customer service team and drives the loyalty programme that rewards thousands of families.',
            'bio_ar' => 'تقود فريق خدمة العملاء وتقود برنامج الولاء الذي يكافئ آلاف العائلات.',
            'avatar' => 'SH',
        ],
    ],

    'news' => [
        [
            'id' => 1,
            'title_en' => 'New Abu Dhabi Store Now Open',
            'title_ar' => 'متجر أبوظبي الجديد مفتوح الآن',
            'summary_en' => 'Our newest location on Al Reem Island brings fresh groceries closer to Abu Dhabi residents.',
            'summary_ar' => 'أحدث فرع لنا على جزيرة الريم يقرب المنتجات الطازجة من سكان أبوظبي.',
            'date' => '2026-07-01',
            'image' => 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600&h=400&fit=crop',
            'category' => 'Company News',
        ],
        [
            'id' => 2,
            'title_en' => 'Organic Week: Up to 30% Off',
            'title_ar' => 'أسبوع العضوي: خصم حتى 30٪',
            'summary_en' => 'Celebrate Organic Week with special discounts on all certified organic products in store and online.',
            'summary_ar' => 'احتفلا بأسبوع العضوي مع خصومات خاصة على جميع المنتجات العضوية المعتمدة في المتجر وأونلاين.',
            'date' => '2026-07-10',
            'image' => 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=600&h=400&fit=crop',
            'category' => 'Promotions',
        ],
        [
            'id' => 3,
            'title_en' => 'Meet Our Local Farmers',
            'title_ar' => 'تعرّفوا على مزارعينا المحليين',
            'summary_en' => 'We partner with 12 local farms across the UAE to bring you the freshest produce straight from the source.',
            'summary_ar' => 'نتشارك مع 12 مزرعة محلية في الإمارات لنقدم لكم أطازج المنتجات مباشرة من المصدر.',
            'date' => '2026-06-20',
            'image' => 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=600&h=400&fit=crop',
            'category' => 'Community',
        ],
        [
            'id' => 4,
            'title_en' => 'Zero Waste Initiative Launched',
            'title_ar' => 'إطلاق مبادرة النفايات الصفارية',
            'summary_en' => 'We are eliminating single-use plastics across all stores by the end of 2026. Bring your own bags and earn bonus loyalty points.',
            'summary_ar' => 'نلغي منتجات البلاستيك لمرة واحدة في جميع الفروع بنهاية 2026. أحضر أكياسك واكسب نقاط ولاء إضافية.',
            'date' => '2026-06-05',
            'image' => 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&h=400&fit=crop',
            'category' => 'Sustainability',
        ],
    ],

    'promo_banners' => [
        [
            'id' => 1,
            'title_en' => 'Summer Fresh Sale',
            'title_ar' => 'عروض الطازج الصيفية',
            'subtitle_en' => 'Up to 30% off on fresh fruits and vegetables',
            'subtitle_ar' => 'خصم حتى 30٪ على الفواكه والخضروات الطازجة',
            'image' => 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=1920&q=100',
            'link' => '/offers',
            'badge_en' => 'LIMITED TIME',
            'badge_ar' => 'لفترة محدودة',
            'bg_color' => '#e8f5e9',
        ],
        [
            'id' => 2,
            'title_en' => 'Free Delivery Weekend',
            'title_ar' => 'توصيل مجاني في عطلة نهاية الأسبوع',
            'subtitle_en' => 'All orders above 50 AED get free delivery this Friday & Saturday',
            'subtitle_ar' => 'جميع الطلبات فوق 50 درهماً تحصل على توصيل مجاني هذا الجمعة والسبت',
            'image' => 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=1920&q=100',
            'link' => '/products',
            'badge_en' => 'THIS WEEKEND',
            'badge_ar' => 'هذا الأسبوع',
            'bg_color' => '#fff3e0',
        ],
        [
            'id' => 3,
            'title_en' => 'New: Premium Seafood Section',
            'title_ar' => 'جديد: قسم المأكولات البحرية الممتازة',
            'subtitle_en' => 'Fresh catch from the Arabian Gulf, delivered daily',
            'subtitle_ar' => 'صيد طازج من الخليج العربي، يُوصل يومياً',
            'image' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1920&q=100',
            'link' => '/products',
            'badge_en' => 'NEW',
            'badge_ar' => 'جديد',
            'bg_color' => '#e3f2fd',
        ],
    ],

    'user' => [
        'id' => 1,
        'name' => 'Aisha Rahman',
        'name_ar' => 'عائشة رحمن',
        'email' => 'aisha.rahman@babalawir.ae',
        'phone' => '+971 50 123 4567',
        'phone_alt' => '+971 50 987 6543',
        'address' => 'Al Awir Road, Dubai, United Arab Emirates',
        'address_ar' => 'شارع العوير، دبي، الإمارات العربية المتحدة',
        'area' => 'Al Awir',
        'city' => 'Dubai',
        'country' => 'UAE',
        'loyalty_points' => 1240,
        'loyalty_tier' => 'Gold',
        'member_since' => '2022-03-14',
        'birthday' => '1990-07-22',
        'preferences' => [
            'language' => 'en',
            'region' => 'ae',
            'notifications' => true,
            'marketing_emails' => false,
            'weekly_newsletter' => true,
        ],
        'saved_addresses' => [
            [
                'label' => 'Home',
                'label_ar' => 'المنزل',
                'address' => 'Al Awir Road, Villa 14, Dubai, UAE',
                'address_ar' => 'شارع العوير، فيلا 14، دبي، الإمارات العربية المتحدة',
                'is_default' => true,
            ],
            [
                'label' => 'Office',
                'label_ar' => 'المكتب',
                'address' => 'Sheikh Zayed Road, Trade Centre Area, Dubai, UAE',
                'address_ar' => 'شارع الشيخ زايد، المنطقة التجارية، دبي، الإمارات العربية المتحدة',
                'is_default' => false,
            ],
        ],
        'orders' => [
            [
                'id' => 'BAW-10892',
                'date' => '2026-07-10',
                'total' => 156.75,
                'status' => 'Shipped',
                'items' => 8,
                'delivery_method' => 'express',
                'estimated_delivery' => '2026-07-10',
            ],
            [
                'id' => 'BAW-10821',
                'date' => '2026-07-01',
                'total' => 42.50,
                'status' => 'Delivered',
                'items' => 3,
                'delivery_method' => 'standard',
                'estimated_delivery' => '2026-07-04',
            ],
            [
                'id' => 'BAW-10765',
                'date' => '2026-06-22',
                'total' => 198.00,
                'status' => 'Delivered',
                'items' => 12,
                'delivery_method' => 'scheduled',
                'estimated_delivery' => '2026-06-24',
            ],
            [
                'id' => 'BAW-10712',
                'date' => '2026-06-15',
                'total' => 73.25,
                'status' => 'Delivered',
                'items' => 5,
                'delivery_method' => 'standard',
                'estimated_delivery' => '2026-06-18',
            ],
            [
                'id' => 'BAW-10648',
                'date' => '2026-06-05',
                'total' => 215.00,
                'status' => 'Delivered',
                'items' => 14,
                'delivery_method' => 'express',
                'estimated_delivery' => '2026-06-05',
            ],
            [
                'id' => 'BAW-10587',
                'date' => '2026-05-20',
                'total' => 89.90,
                'status' => 'Delivered',
                'items' => 6,
                'delivery_method' => 'standard',
                'estimated_delivery' => '2026-05-23',
            ],
         ],
     ],

    'brands' => [
        ['id' => 1, 'name' => 'Almarai', 'logo' => 'https://www.google.com/s2/favicons?domain=almarai.com&sz=128'],
        ['id' => 2, 'name' => 'Nadec', 'logo' => 'https://www.google.com/s2/favicons?domain=nadec.com&sz=128'],
        ['id' => 3, 'name' => 'Lacnor', 'logo' => 'https://www.google.com/s2/favicons?domain=lacnor.com&sz=128'],
        ['id' => 4, 'name' => 'Americana', 'logo' => 'https://www.google.com/s2/favicons?domain=americana-uae.com&sz=128'],
        ['id' => 5, 'name' => 'Nestlé', 'logo' => 'https://www.google.com/s2/favicons?domain=nestle.com&sz=128'],
        ['id' => 6, 'name' => 'Pepsi', 'logo' => 'https://www.google.com/s2/favicons?domain=pepsi.com&sz=128'],
        ['id' => 7, 'name' => 'Coca-Cola', 'logo' => 'https://www.google.com/s2/favicons?domain=coca-cola.com&sz=128'],
        ['id' => 8, 'name' => 'Kellogg\'s', 'logo' => 'https://www.google.com/s2/favicons?domain=kelloggs.com&sz=128'],
        ['id' => 9, 'name' => 'Lipton', 'logo' => 'https://www.google.com/s2/favicons?domain=lipton.com&sz=128'],
        ['id' => 10, 'name' => 'Unilever', 'logo' => 'https://www.google.com/s2/favicons?domain=unilever.com&sz=128'],
        ['id' => 11, 'name' => 'Yaumi', 'logo' => 'https://www.google.com/s2/favicons?domain=yaumi.com&sz=128', 'origin' => 'UAE', 'description_en' => 'Bread brand by Al Rashed Food Company', 'description_ar' => 'ماركة خبز من شركة الفط foods'],
        ['id' => 12, 'name' => 'Al Safa Milk', 'logo' => 'https://www.google.com/s2/favicons?domain=alsafadairy.ae&sz=128', 'origin' => 'UAE', 'description_en' => 'UHT full cream milk brand', 'description_ar' => 'ماركة حليب UHT كامل الدسم'],
        ['id' => 13, 'name' => 'Al Rabi', 'logo' => 'https://www.google.com/s2/favicons?domain=alrabie.com&sz=128', 'origin' => 'UAE', 'description_en' => 'UAE dairy and food brand', 'description_ar' => 'ماركة غذائية من الإمارات'],
        ['id' => 14, 'name' => 'Al Ain Dairy', 'logo' => 'https://www.google.com/s2/favicons?domain=alaindairy.com&sz=128', 'origin' => 'UAE', 'description_en' => 'UAE dairy producer', 'description_ar' => 'منتج ألبان من العين'],
        ['id' => 15, 'name' => 'National Food Industries', 'logo' => 'https://www.google.com/s2/favicons?domain=nfidubai.com&sz=128', 'origin' => 'UAE', 'description_en' => 'UAE food manufacturing company', 'description_ar' => 'شركة غذائية وطنية'],
    ],

    'auth' => [
        'password' => 'password123',
        'token' => 'baw_live_demo_token_a1b2c3d4e5',
        'reset_message' => 'If an account exists for that email, a reset link has been sent to your inbox.',
        'reset_message_ar' => 'إذا كان هناك حساب لهذا البريد، فتم إرسال رابط إعادة تعيين إلى بريدك.',
        'users' => [
            [
                'id' => 1,
                'name' => 'Aisha Rahman',
                'name_ar' => 'عائشة رحمن',
                'email' => 'aisha.rahman@babalawir.ae',
                'phone' => '+971 50 123 4567',
                'password' => 'password123',
            ],
            [
                'id' => 2,
                'name' => 'Khalid Al Maktoum',
                'name_ar' => 'خالد المكتوم',
                'email' => 'khalid.al@babalawir.ae',
                'phone' => '+971 50 987 6543',
                'password' => 'password123',
            ],
        ],
    ],

];
